name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3'
      - name: Build & Unit Tests
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          spm-package: ./
          scheme: RecoilSwift
          destination: platform=iOS Simulator,name=iPhone 14,OS=16.4
          enable-code-coverage: true
          action: test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
